"""PDF forensic report generation with ReportLab."""

from __future__ import annotations

from datetime import datetime, timezone
from pathlib import Path

from reportlab.lib import colors
from reportlab.lib.pagesizes import A4
from reportlab.lib.styles import ParagraphStyle, getSampleStyleSheet
from reportlab.lib.units import inch
from reportlab.platypus import Paragraph, SimpleDocTemplate, Spacer, Table, TableStyle

from app.core.config import get_settings


def _utc_now_str() -> str:
    return datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")


def generate_report(
    *,
    detection_id: int,
    filename: str,
    prediction: str,
    confidence: float,
    frames_analyzed: int,
    suspicious_frames: int,
    model_name: str,
    model_version: str,
    processing_time_sec: float,
    media_type: str,
) -> Path:
    settings = get_settings()
    out_path = settings.reports_dir / f"report_{detection_id}.pdf"

    styles = getSampleStyleSheet()
    title_style = ParagraphStyle(
        "DeepGuardTitle",
        parent=styles["Heading1"],
        fontSize=22,
        textColor=colors.HexColor("#0B3D2E"),
        spaceAfter=6,
    )
    subtitle = ParagraphStyle(
        "DeepGuardSub",
        parent=styles["Normal"],
        fontSize=11,
        textColor=colors.HexColor("#3D5A4C"),
        spaceAfter=18,
    )

    doc = SimpleDocTemplate(str(out_path), pagesize=A4, topMargin=0.75 * inch)
    story = [
        Paragraph("DEEPGUARD AI", title_style),
        Paragraph("Forensic Deepfake Detection Report", subtitle),
        Spacer(1, 8),
    ]

    pred_color = colors.HexColor("#B42318") if prediction == "FAKE" else colors.HexColor("#027A48")
    data = [
        ["Field", "Value"],
        ["Report ID", str(detection_id)],
        ["File", filename],
        ["Media type", media_type],
        ["Result", prediction],
        ["Confidence", f"{confidence * 100:.1f}%"],
        ["Frames analyzed", str(frames_analyzed)],
        ["Suspicious frames", str(suspicious_frames)],
        ["Model", f"{model_name} ({model_version})"],
        ["Processing time", f"{processing_time_sec:.2f} seconds"],
        ["Generated at", _utc_now_str()],
    ]

    table = Table(data, colWidths=[2.2 * inch, 4.2 * inch])
    table.setStyle(
        TableStyle(
            [
                ("BACKGROUND", (0, 0), (-1, 0), colors.HexColor("#0B3D2E")),
                ("TEXTCOLOR", (0, 0), (-1, 0), colors.white),
                ("FONTNAME", (0, 0), (-1, 0), "Helvetica-Bold"),
                ("FONTNAME", (0, 1), (0, -1), "Helvetica-Bold"),
                ("FONTSIZE", (0, 0), (-1, -1), 10),
                ("GRID", (0, 0), (-1, -1), 0.4, colors.HexColor("#D0D5DD")),
                ("BACKGROUND", (0, 1), (-1, -1), colors.HexColor("#F8FAF9")),
                ("TEXTCOLOR", (1, 4), (1, 4), pred_color),
                ("FONTNAME", (1, 4), (1, 4), "Helvetica-Bold"),
                ("VALIGN", (0, 0), (-1, -1), "MIDDLE"),
                ("LEFTPADDING", (0, 0), (-1, -1), 10),
                ("RIGHTPADDING", (0, 0), (-1, -1), 10),
                ("TOPPADDING", (0, 0), (-1, -1), 8),
                ("BOTTOMPADDING", (0, 0), (-1, -1), 8),
            ]
        )
    )
    story.append(table)
    story.append(Spacer(1, 24))
    story.append(
        Paragraph(
            "This report was generated automatically by DeepGuard AI. "
            "Results should be interpreted as decision-support evidence, not absolute proof.",
            styles["Italic"],
        )
    )
    story.append(Spacer(1, 8))
    story.append(Paragraph("Generated by DeepGuard AI", styles["Normal"]))
    doc.build(story)
    return out_path
